$ANSIBLE_VAULT;1.1;AES256
64363766616138316537306165313138613338366434636665646261653033363131323164396362
3239346366626364366239323838656434346631363033390a333633353338333863346336663431
65653766363530333733373739363266646531353434393264663065373339366630663063633135
3130613766623435350a323439336663643061663863313264663834383938376537616162326234
64623237646637326265376638366334316135643034333637346264346535323836373561306533
36663332643934666538633431643362636465363736623738323633663437393332356138313365
34623037346234303235643733633531656533383866353735323361633031313638373865656536
35386336363134663031396430336233653664363436323466316234353233336135316331613333
65393831333239336461633333343635376239323238383637333539643862313465613437306332
30323637633738343636363465343631616634386231613237386134386432353935356562356532
65323363383865356365336235356238356566653263363763363734633839633534636533326439
35303339336437356363336435383064323238663639623930323864633139613337393638303733
30333563663439393564306561346635623438343733643236313632393036663866666437386262
37383337633665373331383264616330663938333264383036313261373138363931353331636130
63623462366234616439306566376265353832663036326130663835306537356431353938396439
66656130343334636639396234373838363835633938386265386565343531626464633938356134
63643266626330633233346536396562363962356330313932363733333934363466
